creation_rules:
  - path_regex: kubernetes/.*\.sops\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: >-
      # REPLACE with your age public key (age1...)
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
