name: Docs

on:
  push:
    branches: [main]
    paths:
      - README.md
      - docs/**

jobs:
  toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: README.md
          TOC_TITLE: "## Table of Contents"
